# Generated by Django 4.0.3 on 2022-06-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
